language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "node"
services:
  - docker
before_install:
  - version=`node --version | grep -oP '(?<=v)\d*?(?=\.)'`
  - docker run --rm node:$version-alpine /bin/sh -c "cd /home/node && apk add --no-cache git build-base python2 && git clone https://github.com/Gniar/zenaddress.git && cd zenaddress && npm install && npm run build"
  - if [[ $version == "12" && "${TRAVIS_PULL_REQUEST}" != "false" ]]; then npm i -g audit-ci && audit-ci --report-type full; fi
