language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"
services:
  - docker
before_install:
  - version=`node --version | grep -oP '(?<=v)\d*?(?=\.)'`
  - branch=`git branch | grep -oP "(?<=^  )(.*)(?=$)"`
  - docker run --rm node:$version-alpine /bin/sh -c "cd /home/node && apk add --no-cache git build-base python2 && git clone https://github.com/Gniar/zenaddress.git && cd zenaddress && git checkout $branch && npm install && npm run build"
  - npm install && npm run build
deploy:
  node_js: "12"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  local_dir: build
  on:
    branch: master
